export function crearObjetoPedido(
  p: any,
  cid: number,
  pid: number,
  rid: number
) {
  let pedido = {
    id: "1110106",
    tamanio: "20 x 20 x 10 cm",
    peso: "1 kg",
    metodo_pago: "4",
    cliente_id: cid,
    status_id: "1",
    fecha_creacion: "2024-08-07 18:22:58",
    fecha_envio: "2024-08-08 14:00:00",
    fecha_recogida: "2024-08-08 09:00:00",
    fecha_entrega: null,
    precio: "58",
    creado_por: "1",
    origen_calle: "Lisboa",
    origen_numero: "1238",
    origen_numero_int: "",
    origen_colonia: "Altaria residencial",
    origen_municipio: "Apodaca",
    origen_estado_id: "1",
    origen_codigo_postal: "66649",
    origen_referencias: "Tavira",
    origen_contacto_nombre: "Grace Flores",
    origen_contacto_tel: "8116206126",
    origen_empresa: "Casa particular",
    entrega_calle: "Priv. Peral",
    entrega_numero: "2612",
    entrega_numero_int: "",
    entrega_colonia: "Moderna",
    entrega_municipio: "Apodaca",
    ent_estado_id: "1",
    entrega_codigo_postal: "69999",
    entrega_referencias: "Camelia y gardenia",
    entrega_contacto_nombre: "Mayra Ortiz",
    entrega_contacto_tel: "8116206126",
    entrega_empresa: "Casa particular",
    comprobante: "",
    origen_nombre: "SYSOP",
    origen_codigo_postal_id: 571,
    entrega_codigo_postal_id: 709,
    origen_municipio_id: 3,
    entrega_municipio_id: 3,
    precio_venta: 68,
    forma_pago_id: 1,
    producto_id: 1,
    guardar_destino_fav: false,
    guardar_paquete_fav: false,
    origen_fecha: "2024-08-08",
    origen_bloque: 1,
    entrega_fecha: "2024-08-08",
    entrega_bloque: 2,
    origen_otra_colonia: 0,
    entrega_otra_colonia: 0,
    paq_volumen_max: 1000,
    paq_alto: 10,
    paq_ancho: 20,
    paq_largo: 20,
    paq_peso: 1,
    paq_tipo_id: 1,
    paq_contenido: "5 moños",
    paq_tipo: "mini",
  };

  //return pedido;
}
